import { useState, useCallback, useRef } from 'react'
import { query } from '../../../services/api.js'
import { ESSAY_SEED_PROMPT, STORAGE_KEY } from '../prompt.js'

// A single entry in the commonplace book.
// Shows the text, source, tags, connections, and the essay seed button.

function loadEntries() {
  try {
    return JSON.parse(localStorage.getItem(STORAGE_KEY)) || []
  } catch {
    return []
  }
}

export default function EntryCard({ entry, allEntries, isExpanded, onToggle }) {
  const [essayState, setEssayState] = useState('idle')
  const [essayData, setEssayData] = useState(null)
  const [essayError, setEssayError] = useState(null)
  const [copied, setCopied] = useState(false)
  const copiedTimeout = useRef(null)

  const connectedEntries = (entry.connected_ids || [])
    .map(id => allEntries.find(e => e.id === id))
    .filter(Boolean)

  const handleEssaySeed = useCallback(async () => {
    setEssayState('loading')
    setEssayError(null)
    setEssayData(null)

    const connected = connectedEntries
      .map(e => `- "${e.text}"${e.source ? ` (${e.source})` : ''}`)
      .join('\n')

    const userMessage = [
      `Primary entry: "${entry.text}"`,
      entry.source ? `Source: ${entry.source}` : '',
      connected ? `\nConnected entries:\n${connected}` : '',
      entry.scholarly_note ? `\nScholar's note on the connection: ${entry.scholarly_note}` : '',
    ].filter(Boolean).join('\n')

    try {
      const raw = await query({
        systemPrompt: ESSAY_SEED_PROMPT,
        userMessage,
      })

      let jsonText = raw.trim()
      const codeBlockMatch = jsonText.match(/```(?:json)?\s*([\s\S]*?)```/)
      if (codeBlockMatch) {
        jsonText = codeBlockMatch[1].trim()
      }

      let result
      try {
        result = JSON.parse(jsonText)
      } catch {
        throw new Error('The essay seed came back illegible. Montaigne blames the ink. Try again.')
      }

      if (!result.reflection) {
        throw new Error('The reflection was empty. Try again.')
      }

      setEssayData(result)
      setEssayState('results')
    } catch (err) {
      setEssayError(err.message)
      setEssayState('error')
    }
  }, [entry, connectedEntries])

  const handleCopy = useCallback(() => {
    if (!essayData) return
    const lines = [
      `# ${essayData.title}`,
      '',
      essayData.reflection,
      '',
      `---`,
      `Seeded from: "${entry.text.slice(0, 80)}${entry.text.length > 80 ? '...' : ''}"`,
      `*Generated by The Commonplace Engine — Vellumere*`,
    ]
    navigator.clipboard.writeText(lines.join('\n'))
    setCopied(true)
    clearTimeout(copiedTimeout.current)
    copiedTimeout.current = setTimeout(() => setCopied(false), 2000)
  }, [essayData, entry])

  const handleDelete = useCallback(() => {
    const entries = loadEntries().filter(e => e.id !== entry.id)
    localStorage.setItem(STORAGE_KEY, JSON.stringify(entries))
    if (onToggle) onToggle(null, true)
  }, [entry.id, onToggle])

  return (
    <article className={`commonplace-entry${isExpanded ? ' expanded' : ''}`}>
      <div className="entry-header" onClick={() => onToggle(entry.id)}>
        <div className="entry-text-preview">
          {isExpanded ? entry.text : (
            entry.text.length > 120 ? entry.text.slice(0, 120) + '...' : entry.text
          )}
        </div>
        <span className="entry-toggle">{isExpanded ? '−' : '+'}</span>
      </div>

      {!isExpanded && entry.tags && (
        <div className="entry-tags-row">
          {entry.tags.map((tag, i) => (
            <span key={i} className="entry-tag-inline">{tag}</span>
          ))}
        </div>
      )}

      {isExpanded && (
        <div className="entry-expanded">
          {entry.source && (
            <p className="entry-source">
              <span className="entry-source-label">Source</span>
              {entry.source}
            </p>
          )}

          {entry.tags && entry.tags.length > 0 && (
            <div className="entry-tags">
              {entry.tags.map((tag, i) => (
                <span key={i} className="entry-tag">{tag}</span>
              ))}
            </div>
          )}

          {entry.scholarly_note && (
            <div className="entry-scholarly-note">
              <span className="entry-note-label">Scholar's Note</span>
              <p>{entry.scholarly_note}</p>
            </div>
          )}

          {connectedEntries.length > 0 && (
            <div className="entry-connections">
              <span className="entry-connections-label">Connected Entries</span>
              {connectedEntries.map(ce => (
                <div key={ce.id} className="entry-connection-item" onClick={() => onToggle(ce.id)}>
                  <p className="entry-connection-text">
                    {ce.text.length > 100 ? ce.text.slice(0, 100) + '...' : ce.text}
                  </p>
                  {ce.source && <span className="entry-connection-source">{ce.source}</span>}
                </div>
              ))}
            </div>
          )}

          <div className="entry-actions">
            <button
              className="essay-seed-btn"
              onClick={handleEssaySeed}
              disabled={essayState === 'loading'}
            >
              {essayState === 'loading' ? 'Growing the seed...' : 'Essay Seed'}
            </button>
            <button className="entry-delete-btn" onClick={handleDelete}>
              Remove
            </button>
          </div>

          {essayState === 'loading' && (
            <p className="essay-loading-text">Montaigne is drafting...</p>
          )}

          {essayState === 'results' && essayData && (
            <div className="essay-result">
              <span className="essay-result-label">Essay Seed</span>
              <h4 className="essay-result-title">{essayData.title}</h4>
              <p className="essay-result-text">{essayData.reflection}</p>
              <button className="essay-copy-btn" onClick={handleCopy}>
                {copied ? '✓ Copied' : '⟢ Keep This Seed'}
              </button>
            </div>
          )}

          {essayState === 'error' && (
            <div className="essay-error">
              <p className="essay-error-text">{essayError}</p>
              <button className="essay-seed-btn" onClick={handleEssaySeed}>
                Try Again
              </button>
            </div>
          )}

          <span className="entry-date">
            {new Date(entry.timestamp).toLocaleDateString('en-US', {
              month: 'short', day: 'numeric', year: 'numeric'
            })}
          </span>
        </div>
      )}
    </article>
  )
}
