import { useState, useCallback, useRef } from 'react'
import { Link } from 'react-router-dom'
import SiteNav from '../../components/SiteNav.jsx'
import SiteFooter from '../../components/SiteFooter.jsx'
import HelpTooltip from '../../components/HelpTooltip.jsx'
import JourneyLink from '../../components/JourneyLink.jsx'
import DecoderInput from './components/DecoderInput.jsx'
import TranslationPanel from './components/TranslationPanel.jsx'
import DecoderLoader from './components/DecoderLoader.jsx'
import { query } from '../../services/api.js'
import { DECODER_PROMPT } from './prompt.js'
import './decoder.css'

// The Decoder
// Medieval translators moved knowledge between Arabic and Latin.
// We move knowledge between Expert, Curious, and Skeptic.
// Same job. Different century.

const PANEL_TYPES = ['expert', 'curious', 'skeptic']
const TAB_LABELS = { expert: 'Expert', curious: 'Curious', skeptic: 'Skeptic' }

export default function Decoder() {
  const [state, setState] = useState('idle')
  const [data, setData] = useState(null)
  const [error, setError] = useState(null)
  const [currentInput, setCurrentInput] = useState('')
  const [copied, setCopied] = useState(false)
  const [activeTab, setActiveTab] = useState('expert')
  const copiedTimeout = useRef(null)

  const handleCopy = useCallback(() => {
    if (!data) return
    const t = data.translations
    const lines = []
    lines.push(`# ${data.input}`)
    lines.push(`*Topic: ${data.topic_detected}*`)
    lines.push('')
    lines.push('---')
    lines.push('')
    lines.push('## The Expert')
    lines.push(`*Assumes: ${t.expert.assumes}*`)
    lines.push('')
    if (t.expert.direct_quote) lines.push(`> "${t.expert.direct_quote}"`)
    lines.push('')
    lines.push(t.expert.text)
    lines.push('')
    lines.push('---')
    lines.push('')
    lines.push('## The Curious')
    lines.push(`*Analogy: ${t.curious.analogy}*`)
    lines.push('')
    if (t.curious.direct_quote) lines.push(`> "${t.curious.direct_quote}"`)
    lines.push('')
    lines.push(t.curious.text)
    lines.push('')
    lines.push('---')
    lines.push('')
    lines.push('## The Skeptic')
    lines.push(`*Bottom line: ${t.skeptic.bottom_line}*`)
    lines.push('')
    if (t.skeptic.direct_quote) lines.push(`> "${t.skeptic.direct_quote}"`)
    lines.push('')
    lines.push(t.skeptic.text)
    lines.push('')
    if (data.lost_in_translation) {
      lines.push('---')
      lines.push('')
      lines.push(`**Lost in Translation:** ${data.lost_in_translation}`)
      lines.push('')
    }
    lines.push(`*Generated by The Decoder — Vellumere*`)
    navigator.clipboard.writeText(lines.join('\n'))
    setCopied(true)
    clearTimeout(copiedTimeout.current)
    copiedTimeout.current = setTimeout(() => setCopied(false), 2000)
  }, [data])

  const handleSubmit = useCallback(async (text) => {
    setCurrentInput(text)
    setState('loading')
    setError(null)
    setData(null)
    setActiveTab('expert')

    try {
      const raw = await query({
        systemPrompt: DECODER_PROMPT,
        userMessage: text,
      })

      let jsonText = raw.trim()
      const codeBlockMatch = jsonText.match(/```(?:json)?\s*([\s\S]*?)```/)
      if (codeBlockMatch) {
        jsonText = codeBlockMatch[1].trim()
      }

      let result
      try {
        result = JSON.parse(jsonText)
      } catch {
        throw new Error("The decoder misfired. Even medieval translators had bad days. Try again.")
      }

      if (!result.translations || !result.translations.expert) {
        throw new Error("The translation came back incomplete. Try again with different text.")
      }

      setData(result)
      setState('results')
    } catch (err) {
      setError(err.message)
      setState('error')
    }
  }, [])

  const handleReset = () => {
    setState('idle')
    setData(null)
    setError(null)
    setCurrentInput('')
    setActiveTab('expert')
  }

  return (
    <div className="the-decoder">
      <SiteNav isToolPage />

      <header className="decoder-header">
        <h1 className="decoder-title" onClick={handleReset} style={{ cursor: 'pointer' }}>
          The Decoder
        </h1>
        <p className="decoder-subtitle">
          Paste something complex. Get three translations — expert, curious, and skeptic.
          <HelpTooltip text="Inspired by medieval translators who moved knowledge between Arabic and European scholarship. Paste any concept and see it translated for three audiences: the Expert (precise, technical), the Curious (clear, warm, analogies), and the Skeptic (blunt, practical, no fluff). The side-by-side view shows how the same idea shapeshifts across audiences." />
        </p>
      </header>

      <main className="decoder-main">
        {/* Input — visible unless showing results */}
        {state !== 'results' && (
          <DecoderInput
            onSubmit={handleSubmit}
            isLoading={state === 'loading'}
            onExampleClick={state === 'idle' ? handleSubmit : null}
          />
        )}

        {/* Idle */}
        {state === 'idle' && (
          <div className="decoder-empty">
            <p className="decoder-empty-text">
              Paste something complex. See it translated for three minds.
            </p>
          </div>
        )}

        {/* Loading */}
        {state === 'loading' && (
          <DecoderLoader />
        )}

        {/* Results */}
        {state === 'results' && data && (
          <div className="decoder-results">
            <div className="decoder-results-header">
              <button className="decoder-back-btn" onClick={handleReset}>
                ← Decode Something Else
              </button>
              <span className="decoder-topic">
                topic: <span className="decoder-topic-value">{data.topic_detected}</span>
              </span>
            </div>

            {/* Mobile tabs */}
            <div className="panel-tabs">
              {PANEL_TYPES.map(type => (
                <button
                  key={type}
                  className={`panel-tab${activeTab === type ? ` active-${type}` : ''}`}
                  onClick={() => setActiveTab(type)}
                >
                  {TAB_LABELS[type]}
                </button>
              ))}
            </div>

            {/* Three panels */}
            <div className="translation-panels">
              {PANEL_TYPES.map(type => (
                <TranslationPanel
                  key={type}
                  type={type}
                  translation={data.translations[type]}
                  isActive={activeTab === type}
                />
              ))}
            </div>

            {/* Lost in Translation */}
            {data.lost_in_translation && (
              <div className="lost-in-translation">
                <span className="lost-label">Lost in Translation</span>
                <p className="lost-text">{data.lost_in_translation}</p>
              </div>
            )}

            <div className="decoder-copy">
              <button className="decoder-copy-btn" onClick={handleCopy}>
                {copied ? '✓ Copied to clipboard' : '⟢ Keep All Three'}
              </button>
              <span className="decoder-copy-hint">Copy as markdown</span>
            </div>
          </div>
        )}

        {/* Error */}
        {state === 'error' && (
          <div className="decoder-error">
            <p className="decoder-error-message">{error}</p>
            <button className="decoder-retry-btn" onClick={() => handleSubmit(currentInput)}>
              Try Again
            </button>
            <button className="decoder-back-btn" onClick={handleReset} style={{ display: 'block', margin: '0.5rem auto' }}>
              ← Start Over
            </button>
          </div>
        )}
      </main>

      {state === 'results' && data && (
        <>
          <div className="contextual-link-container">
            <Link to="/examination" className="contextual-link">
              Reflect on what you learned today →
            </Link>
          </div>
          <JourneyLink currentRoute="/decoder" />
        </>
      )}
      <SiteFooter />
    </div>
  )
}
