import { useState, useCallback, useRef } from 'react'
import SiteNav from '../../components/SiteNav.jsx'
import SiteFooter from '../../components/SiteFooter.jsx'
import HelpTooltip from '../../components/HelpTooltip.jsx'
import PermissionInput from './components/PermissionInput.jsx'
import FigureCard from './components/FigureCard.jsx'
import PatternLine from './components/PatternLine.jsx'
import PermissionLoader from './components/PermissionLoader.jsx'
import { query } from '../../services/api.js'
import { PERMISSION_PROMPT } from './prompt.js'
import './permission.css'

// The Permission Machine
// You don't need a credential. You need a precedent.
// Here are three people who already proved it's possible.

export default function Permission() {
  const [state, setState] = useState('idle')
  const [data, setData] = useState(null)
  const [error, setError] = useState(null)
  const [currentDesire, setCurrentDesire] = useState('')
  const [copied, setCopied] = useState(false)
  const copiedTimeout = useRef(null)

  const handleCopy = useCallback(() => {
    if (!data) return
    const lines = []
    lines.push(`# I want to ${data.desire}`)
    lines.push('')
    data.figures.forEach((f, i) => {
      lines.push(`## ${i + 1}. ${f.name} (${f.lived})`)
      lines.push('')
      lines.push(f.what_they_did)
      lines.push('')
      lines.push(`**The Barrier:** ${f.the_barrier}`)
      lines.push('')
      lines.push(`**How Anyway:** ${f.how_anyway}`)
      lines.push('')
      lines.push(`> *${f.permission_line}*`)
      lines.push('')
      if (f.wikipedia_url) {
        lines.push(`[Read more about ${f.name}](${f.wikipedia_url})`)
        lines.push('')
      }
      lines.push('---')
      lines.push('')
    })
    if (data.the_pattern) {
      lines.push(`**The Pattern:** ${data.the_pattern}`)
      lines.push('')
    }
    lines.push(`*Generated by The Permission Machine — Vellumere*`)
    navigator.clipboard.writeText(lines.join('\n'))
    setCopied(true)
    clearTimeout(copiedTimeout.current)
    copiedTimeout.current = setTimeout(() => setCopied(false), 2000)
  }, [data])

  const handleSubmit = useCallback(async (desire) => {
    setCurrentDesire(desire)
    setState('loading')
    setError(null)
    setData(null)

    try {
      const raw = await query({
        systemPrompt: PERMISSION_PROMPT,
        userMessage: desire.trim(),
      })

      // Parse JSON — handle markdown code block wrapping
      let jsonText = raw.trim()
      const codeBlockMatch = jsonText.match(/```(?:json)?\s*([\s\S]*?)```/)
      if (codeBlockMatch) {
        jsonText = codeBlockMatch[1].trim()
      }

      let result
      try {
        result = JSON.parse(jsonText)
      } catch {
        throw new Error("The archives returned something we couldn't read. Try again — the figures are still out there.")
      }

      if (!result.figures || !Array.isArray(result.figures) || result.figures.length === 0) {
        throw new Error("History couldn't find an exact match. But that might mean you'd be the first. That's even better.")
      }

      setData(result)
      setState('results')
    } catch (err) {
      setError(err.message)
      setState('error')
    }
  }, [])

  const handleReset = () => {
    setState('idle')
    setData(null)
    setError(null)
    setCurrentDesire('')
  }

  return (
    <div className="the-permission-machine">
      <SiteNav isToolPage />

      <header className="permission-header">
        <h1 className="permission-title" onClick={handleReset} style={{ cursor: 'pointer' }}>
          The Permission Machine
        </h1>
        <p className="permission-subtitle">
          You don't need a credential. You need a precedent.
          <HelpTooltip text="The Permission Machine finds real historical figures who did exactly what you want to do — without the credentials, background, or permission that people assume you need. Type what you want to become or do, and meet three people who already proved it's possible." />
        </p>
      </header>

      <main className="permission-main">
        {/* Input — always visible unless showing results */}
        {state !== 'results' && (
          <PermissionInput
            onSubmit={handleSubmit}
            isLoading={state === 'loading'}
            onExampleClick={state === 'idle' ? handleSubmit : null}
          />
        )}

        {/* Idle state */}
        {state === 'idle' && (
          <div className="permission-empty">
            <p className="permission-empty-question">What do you want permission to do?</p>
            <p className="permission-empty-hint">Click an example above, or type your own.</p>
          </div>
        )}

        {/* Loading */}
        {state === 'loading' && (
          <PermissionLoader />
        )}

        {/* Results */}
        {state === 'results' && data && (
          <div className="permission-results">
            <div className="permission-results-header">
              <button className="permission-back-btn" onClick={handleReset}>
                ← Ask Again
              </button>
              <h2 className="permission-desire">"I want to {data.desire}"</h2>
            </div>

            {data.figures.map((figure, i) => (
              <FigureCard key={figure.name} figure={figure} index={i} />
            ))}

            {data.the_pattern && (
              <PatternLine pattern={data.the_pattern} />
            )}

            <div className="permission-copy">
              <button className="permission-copy-btn" onClick={handleCopy}>
                {copied ? '✓ Copied to clipboard' : '⟢ Keep These Stories'}
              </button>
              <span className="permission-copy-hint">Copy as markdown</span>
            </div>
          </div>
        )}

        {/* Error */}
        {state === 'error' && (
          <div className="permission-error">
            <p className="permission-error-message">{error}</p>
            <button className="permission-retry-btn" onClick={() => handleSubmit(currentDesire)}>
              Try Again
            </button>
            <button className="permission-back-btn" onClick={handleReset} style={{ display: 'block', margin: '0.5rem auto' }}>
              ← Start Over
            </button>
          </div>
        )}
      </main>

      <SiteFooter />
    </div>
  )
}
