import { useState, useCallback, useRef, useEffect } from 'react'
import { Link, useSearchParams } from 'react-router-dom'
import SiteNav from '../../components/SiteNav.jsx'
import SiteFooter from '../../components/SiteFooter.jsx'
import HelpTooltip from '../../components/HelpTooltip.jsx'
import JourneyLink from '../../components/JourneyLink.jsx'
import SkillInput from './components/SkillInput.jsx'
import PhaseCard from './components/PhaseCard.jsx'
import ApprenticeshipLoader from './components/ApprenticeshipLoader.jsx'
import { query } from '../../services/api.js'
import { APPRENTICESHIP_PROMPT } from './prompt.js'
import './apprenticeship.css'

// The Apprenticeship
// A guild master's roadmap for learning anything.
// Four phases. From first week to lifelong practice.

export default function Apprenticeship() {
  const [state, setState] = useState('idle')
  const [data, setData] = useState(null)
  const [error, setError] = useState(null)
  const [currentSkill, setCurrentSkill] = useState('')
  const [copied, setCopied] = useState(false)
  const copiedTimeout = useRef(null)

  // URL parameter support — Permission Machine links here with ?skill=
  const [searchParams] = useSearchParams()
  const skillFromUrl = searchParams.get('skill')
  const hasAutoSubmitted = useRef(false)

  const handleCopy = useCallback(() => {
    if (!data) return
    const lines = []
    lines.push(`# ${data.guild_title || data.skill}`)
    lines.push('')
    if (data.overview) {
      lines.push(data.overview)
      lines.push('')
      lines.push('---')
      lines.push('')
    }
    data.phases.forEach(phase => {
      lines.push(`## Phase ${phase.number}: ${phase.name}`)
      lines.push(`*${phase.subtitle}*`)
      lines.push('')
      if (phase.safety) {
        lines.push(`**⚠ Safety First:** ${phase.safety}`)
        lines.push('')
      }
      phase.actions.forEach((action, i) => {
        lines.push(`${i + 1}. ${action}`)
      })
      lines.push('')
      if (phase.avoid) {
        lines.push(`**Avoid This:** ${phase.avoid}`)
        lines.push('')
      }
      if (phase.ready_when) {
        lines.push(`**Ready When:** ${phase.ready_when}`)
        lines.push('')
      }
      if (phase.resources && phase.resources.length > 0) {
        lines.push('**Resources:**')
        phase.resources.forEach(r => {
          lines.push(`- ${r.name} (${r.type}, ${r.cost}) — ${r.why}`)
        })
        lines.push('')
      }
      lines.push('---')
      lines.push('')
    })
    if (data.master_note) {
      lines.push(`> *${data.master_note}*`)
      lines.push('')
    }
    lines.push('*Generated by The Apprenticeship — Vellumere*')
    navigator.clipboard.writeText(lines.join('\n'))
    setCopied(true)
    clearTimeout(copiedTimeout.current)
    copiedTimeout.current = setTimeout(() => setCopied(false), 2000)
  }, [data])

  const handleSubmit = useCallback(async (skill) => {
    setCurrentSkill(skill)
    setState('loading')
    setError(null)
    setData(null)

    try {
      const raw = await query({
        systemPrompt: APPRENTICESHIP_PROMPT,
        userMessage: skill.trim(),
      })

      // Parse JSON — handle markdown code block wrapping
      let jsonText = raw.trim()
      const codeBlockMatch = jsonText.match(/```(?:json)?\s*([\s\S]*?)```/)
      if (codeBlockMatch) {
        jsonText = codeBlockMatch[1].trim()
      }

      let result
      try {
        result = JSON.parse(jsonText)
      } catch {
        throw new Error('The guild masters returned a scroll we could not read. Try again — the path is still being drafted.')
      }

      if (!result.phases || !Array.isArray(result.phases) || result.phases.length === 0) {
        throw new Error('The roadmap came back empty. Even a master needs a second attempt sometimes.')
      }

      setData(result)
      setState('results')
    } catch (err) {
      setError(err.message)
      setState('error')
    }
  }, [])

  // Auto-submit when arriving from Permission Machine with ?skill= param
  useEffect(() => {
    if (skillFromUrl && !hasAutoSubmitted.current) {
      hasAutoSubmitted.current = true
      handleSubmit(skillFromUrl)
    }
  }, [skillFromUrl, handleSubmit])

  const handleReset = () => {
    setState('idle')
    setData(null)
    setError(null)
    setCurrentSkill('')
  }

  return (
    <div className="the-apprenticeship">
      <SiteNav isToolPage />

      <header className="apprenticeship-header">
        <h1 className="apprenticeship-title" onClick={handleReset} style={{ cursor: 'pointer' }}>
          The Apprenticeship
        </h1>
        <p className="apprenticeship-subtitle">
          Tell us what you want to learn. We'll map the path from novice to craftsman.
          <HelpTooltip text="Inspired by medieval guild progression — Apprentice, Journeyman, Master. Type any skill you want to learn and get a four-phase roadmap: your first week, your first month, months 2-6 of deepening, and the ongoing path. Every step is specific and doable. No vague advice, no impossible standards." />
        </p>
      </header>

      <main className="apprenticeship-main">
        {/* Input — always visible unless showing results */}
        {state !== 'results' && (
          <SkillInput
            onSubmit={handleSubmit}
            isLoading={state === 'loading'}
            onExampleClick={state === 'idle' ? handleSubmit : null}
            initialValue={skillFromUrl || ''}
          />
        )}

        {/* Idle state */}
        {state === 'idle' && (
          <div className="apprenticeship-empty">
            <p className="apprenticeship-empty-question">What do you want to learn?</p>
            <p className="apprenticeship-empty-hint">
              Type a skill, a craft, a discipline — anything you've been wanting to start.
              We'll map the path from beginner to practitioner.
            </p>
          </div>
        )}

        {/* Loading */}
        {state === 'loading' && (
          <ApprenticeshipLoader />
        )}

        {/* Results */}
        {state === 'results' && data && (
          <div className="apprenticeship-results">
            <div className="apprenticeship-results-header">
              <button className="apprenticeship-back-btn" onClick={handleReset}>
                ← Learn Something Else
              </button>
              <h2 className="apprenticeship-guild-title">
                {data.guild_title || `Learning: ${data.skill}`}
              </h2>
              <p className="apprenticeship-skill">{data.skill}</p>
            </div>

            {data.overview && (
              <p className="apprenticeship-overview">{data.overview}</p>
            )}

            <div className="phase-timeline">
              {data.phases.map((phase, i) => (
                <PhaseCard key={phase.number || i} phase={phase} index={i} />
              ))}
            </div>

            {data.master_note && (
              <div className="apprenticeship-master-note">
                <span className="apprenticeship-master-note-label">From the Master</span>
                <p className="apprenticeship-master-note-text">"{data.master_note}"</p>
              </div>
            )}

            <div className="apprenticeship-copy">
              <button className="apprenticeship-copy-btn" onClick={handleCopy}>
                {copied ? '✓ Copied to clipboard' : '⟢ Keep This Roadmap'}
              </button>
              <span className="apprenticeship-copy-hint">Copy as markdown</span>
            </div>
          </div>
        )}

        {/* Error */}
        {state === 'error' && (
          <div className="apprenticeship-error">
            <p className="apprenticeship-error-message">{error}</p>
            <button className="apprenticeship-retry-btn" onClick={() => handleSubmit(currentSkill)}>
              Try Again
            </button>
            <button className="apprenticeship-back-btn" onClick={handleReset} style={{ display: 'block', margin: '0.5rem auto' }}>
              ← Start Over
            </button>
          </div>
        )}
      </main>

      {state === 'results' && data && (
        <>
          <div className="contextual-link-container">
            <Link
              to={`/connessione?topic=${encodeURIComponent(data.skill)}`}
              className="contextual-link"
            >
              Want cross-domain techniques for {data.skill}? →
            </Link>
          </div>
          <JourneyLink currentRoute="/apprenticeship" />
        </>
      )}
      <SiteFooter />
    </div>
  )
}
