import { useState, useCallback, useRef } from 'react'
import SiteNav from '../../components/SiteNav.jsx'
import SiteFooter from '../../components/SiteFooter.jsx'
import ApiKeyModal from '../../components/ApiKeyModal.jsx'
import HelpTooltip from '../../components/HelpTooltip.jsx'
import NotebookPage from './components/NotebookPage.jsx'
import ConceptInput from './components/ConceptInput.jsx'
import ConnectionGraph from './components/ConnectionGraph.jsx'
import ResonanceLoader from './components/ResonanceLoader.jsx'
import { query, hasApiKey } from '../../services/api.js'
import { CONNESSIONE_PROMPT } from './prompt.js'
import './connessione.css'

// The Connessione Engine
// Built by an AI pretending three dead geniuses told it what to do.
// We are all aware of the irony. We are all okay with it.

// States: idle → loading → results → error → no_key
// Like the four humors, but for React components. (Five if you count Franklin's impatience.)

export default function Connessione() {
  const [state, setState] = useState('idle')
  const [data, setData] = useState(null)
  const [error, setError] = useState(null)
  const [currentConcept, setCurrentConcept] = useState('')
  const [showSettings, setShowSettings] = useState(false)
  const [copied, setCopied] = useState(false)
  const copiedTimeout = useRef(null)

  const handleGatherThreads = useCallback(() => {
    if (!data) return
    const lines = []
    lines.push(`# ${data.input_concept}`)
    lines.push('')
    if (data.core_pattern) {
      lines.push(`**Core Pattern:** ${data.core_pattern}`)
      lines.push('')
    }
    lines.push('---')
    lines.push('')
    data.connections.forEach((c, i) => {
      lines.push(`## ${i + 1}. ${c.domain} — ${c.title}`)
      lines.push('')
      const thread = c.transfer || c.pattern || ''
      if (thread) {
        lines.push(`**The Thread:** ${thread}`)
        lines.push('')
      }
      if (c.so_what) {
        lines.push(`**So What?** ${c.so_what}`)
        lines.push('')
      }
      if (c.leonardo_note) {
        lines.push(`> ✎ ${c.leonardo_note}`)
        lines.push('')
      }
      lines.push('---')
      lines.push('')
    })
    if (data.meta_insight) {
      lines.push(`**The Overarching Pattern:** ${data.meta_insight}`)
      lines.push('')
    }
    lines.push(`*Generated by The Connessione Engine — Vellumere*`)
    navigator.clipboard.writeText(lines.join('\n'))
    setCopied(true)
    clearTimeout(copiedTimeout.current)
    copiedTimeout.current = setTimeout(() => setCopied(false), 2000)
  }, [data])

  const handleSubmit = useCallback(async (concept) => {
    setCurrentConcept(concept)
    setState('loading')
    setError(null)
    setData(null)

    if (!hasApiKey()) {
      setState('no_key')
      return
    }

    try {
      const raw = await query({
        systemPrompt: CONNESSIONE_PROMPT,
        userMessage: concept.trim(),
      })

      // Parse JSON from Claude's response
      // Sometimes Claude wraps JSON in markdown code blocks
      let jsonText = raw.trim()
      const codeBlockMatch = jsonText.match(/```(?:json)?\s*([\s\S]*?)```/)
      if (codeBlockMatch) {
        jsonText = codeBlockMatch[1].trim()
      }

      let result
      try {
        result = JSON.parse(jsonText)
      } catch {
        throw new Error("Three geniuses and we still can't parse that. The response came back as something other than valid JSON. The apprentice is embarrassed.")
      }

      // Validate the structure (Franklin insists on quality control)
      if (!result.connections || !Array.isArray(result.connections) || result.connections.length === 0) {
        throw new Error("The engine returned connections in a format even Leonardo can't decipher. Try a different concept.")
      }

      setData(result)
      setState('results')
    } catch (err) {
      if (err.message === 'NO_API_KEY') {
        setState('no_key')
      } else {
        setError(err.message)
        setState('error')
      }
    }
  }, [])

  const handleExploreDeeper = useCallback((domain) => {
    handleSubmit(domain)
  }, [handleSubmit])

  const handleReset = () => {
    setState('idle')
    setData(null)
    setError(null)
    setCurrentConcept('')
  }

  return (
    <div className="the-engine">
      <SiteNav onOpenSettings={() => setShowSettings(true)} isToolPage />
      <ApiKeyModal isOpen={showSettings} onClose={() => setShowSettings(false)} />

      <header className="engine-header">
        <h1 className="engine-title" onClick={handleReset} style={{ cursor: 'pointer' }}>
          The Connessione Engine
        </h1>
        <p className="engine-subtitle">
          Enter any topic. Discover techniques from other fields that can transform your approach.
          <HelpTooltip text="The Connessione Engine finds techniques and methods from unexpected fields that can directly improve how you think about any topic. Type a concept — broad or specific — and discover new approaches imported from domains you'd never think to look at. Inspired by Leonardo da Vinci's principle that everything connects, and David Epstein's research on how generalists solve problems by transferring knowledge across boundaries." />
        </p>
      </header>

      <main className="engine-main">
        <NotebookPage>
          {/* The input — always visible at top */}
          <ConceptInput
            onSubmit={handleSubmit}
            isLoading={state === 'loading'}
          />

          {/* Idle / Empty state */}
          {state === 'idle' && (
            <div className="empty-state">
              <div className="empty-state-illustration">
                <svg viewBox="0 0 200 120" className="empty-doodle">
                  <circle cx="60" cy="60" r="20" fill="none" stroke="var(--slate)" strokeWidth="1" strokeDasharray="4 3" />
                  <circle cx="140" cy="60" r="20" fill="none" stroke="var(--slate)" strokeWidth="1" strokeDasharray="4 3" />
                  <circle cx="100" cy="30" r="20" fill="none" stroke="var(--slate)" strokeWidth="1" strokeDasharray="4 3" />
                  <path d="M 75 50 Q 100 40 125 50" fill="none" stroke="var(--honey)" strokeWidth="0.8" strokeOpacity="0.4" />
                  <path d="M 68 75 Q 100 95 132 75" fill="none" stroke="var(--honey)" strokeWidth="0.8" strokeOpacity="0.4" />
                  <path d="M 80 42 Q 85 35 92 35" fill="none" stroke="var(--honey)" strokeWidth="0.8" strokeOpacity="0.4" />
                  <text x="100" y="115" textAnchor="middle" className="empty-doodle-text" fill="var(--slate)" fontSize="8">everything is connected</text>
                </svg>
              </div>
              <p className="empty-state-text">
                The council awaits your inquiry.
              </p>
              <p className="empty-state-hint">
                Try: "public speaking" · "3D printing tolerances" · "gardening" · "negotiation tactics"
              </p>
            </div>
          )}

          {/* Loading state — Tesla's resonance */}
          {state === 'loading' && (
            <ResonanceLoader />
          )}

          {/* Results — The full graph and cards */}
          {state === 'results' && data && (
            <div className="results-container">
              <div className="results-header">
                <button className="back-btn" onClick={handleReset}>
                  ← New Concept
                </button>
                <h2 className="results-concept">{data.input_concept}</h2>
              </div>

              <ConnectionGraph
                data={data}
                onExploreDeeper={handleExploreDeeper}
              />

              {/* Meta-insight — the scholar's concluding note */}
              {data.meta_insight && (
                <div className="meta-insight">
                  <span className="meta-insight-label">The Overarching Pattern</span>
                  <p>{data.meta_insight}</p>
                  <p className="meta-insight-attribution">
                    — Observed by three minds, synthesized by a machine, offered to a human
                  </p>
                </div>
              )}

              <div className="gather-threads">
                <button className="gather-threads-btn" onClick={handleGatherThreads}>
                  {copied ? '✓ Copied to clipboard' : '⟢ Gather the Threads'}
                </button>
                <span className="gather-threads-hint">Copy as markdown</span>
              </div>
            </div>
          )}

          {/* No API key state — Franklin's favorite complaint */}
          {state === 'no_key' && (
            <div className="error-state">
              <p className="no-key-message">
                Franklin says nothing in life is free, including API calls.
                Click the gear icon to enter your Anthropic API key.
              </p>
              <button className="retry-btn" onClick={() => setShowSettings(true)}>
                Open Settings — Appease Franklin
              </button>
            </div>
          )}

          {/* Error state — the apprentice broke something */}
          {state === 'error' && (
            <div className="error-state">
              <p className="error-message">{error}</p>
              <button className="retry-btn" onClick={() => handleSubmit(currentConcept)}>
                Try Again — The apprentice promises to do better
              </button>
              <button className="back-btn" onClick={handleReset}>
                ← Start Over
              </button>
            </div>
          )}
        </NotebookPage>
      </main>

      {/* Bottega byline */}
      <div className="bottega-byline">
        <p>
          A <em>Bottega del Caos</em> contraption. No geniuses were consulted. Several were hallucinated.
        </p>
      </div>

      <SiteFooter />
    </div>
  )
}
