import { useState, useCallback, useRef, useEffect } from 'react'
import { Link, useSearchParams } from 'react-router-dom'
import SiteNav from '../../components/SiteNav.jsx'
import SiteFooter from '../../components/SiteFooter.jsx'
import HelpTooltip from '../../components/HelpTooltip.jsx'
import JourneyLink from '../../components/JourneyLink.jsx'
import DomainSelector from './components/DomainSelector.jsx'
import CollisionCard from './components/CollisionCard.jsx'
import CombinatoriLoader from './components/CombinatoriLoader.jsx'
import { query } from '../../services/api.js'
import { COMBINATORIA_PROMPT } from './prompt.js'
import './combinatoria.css'

// The Ars Combinatoria
// Ramon Llull built a paper wheel in 1305 to systematically combine concepts.
// 720 years later, we're doing the same thing with React.
// Progress.

export default function Combinatoria() {
  const [state, setState] = useState('idle')
  const [data, setData] = useState(null)
  const [error, setError] = useState(null)
  const [currentDomains, setCurrentDomains] = useState({ a: '', b: '' })
  const [copied, setCopied] = useState(false)
  const copiedTimeout = useRef(null)

  // URL parameter support — Connessione links here with ?domain_a=
  const [searchParams] = useSearchParams()
  const domainAFromUrl = searchParams.get('domain_a')

  const handleCopy = useCallback(() => {
    if (!data) return
    const lines = []
    lines.push(`# ${data.domain_a} × ${data.domain_b}`)
    lines.push('')
    if (data.collision_point) {
      lines.push(`**Collision Point:** ${data.collision_point}`)
      lines.push('')
    }
    lines.push('---')
    lines.push('')
    data.results.forEach((r, i) => {
      lines.push(`## ${i + 1}. ${r.title}`)
      lines.push(`*${r.type}*`)
      lines.push('')
      lines.push(r.what_it_is)
      lines.push('')
      lines.push(`**From ${data.domain_a}:** ${r.from_domain_a}`)
      lines.push(`**From ${data.domain_b}:** ${r.from_domain_b}`)
      lines.push('')
      lines.push(`**Why it works:** ${r.why_it_works}`)
      lines.push('')
      lines.push(`**First step:** ${r.first_step}`)
      lines.push('')
      if (r.reference_url) {
        lines.push(`[${r.type === 'existing' ? 'Read more' : 'Start exploring'}](${r.reference_url})`)
        lines.push('')
      }
      lines.push('---')
      lines.push('')
    })
    if (data.llull_note) {
      lines.push(`> *${data.llull_note}*`)
      lines.push('')
    }
    lines.push(`*Generated by The Ars Combinatoria — Vellumere*`)
    navigator.clipboard.writeText(lines.join('\n'))
    setCopied(true)
    clearTimeout(copiedTimeout.current)
    copiedTimeout.current = setTimeout(() => setCopied(false), 2000)
  }, [data])

  const handleCollide = useCallback(async (domainA, domainB) => {
    setCurrentDomains({ a: domainA, b: domainB })
    setState('loading')
    setError(null)
    setData(null)

    try {
      const raw = await query({
        systemPrompt: COMBINATORIA_PROMPT,
        userMessage: `Domain A: ${domainA}\nDomain B: ${domainB}`,
      })

      // Parse JSON — handle markdown code block wrapping
      let jsonText = raw.trim()
      const codeBlockMatch = jsonText.match(/```(?:json)?\s*([\s\S]*?)```/)
      if (codeBlockMatch) {
        jsonText = codeBlockMatch[1].trim()
      }

      let result
      try {
        result = JSON.parse(jsonText)
      } catch {
        throw new Error("The wheels spun but the output was illegible. Llull blames the printing press. Try again.")
      }

      if (!result.results || !Array.isArray(result.results) || result.results.length === 0) {
        throw new Error("The collision produced no debris. These domains might be too similar — or the wheels jammed. Try different inputs.")
      }

      setData(result)
      setState('results')
    } catch (err) {
      setError(err.message)
      setState('error')
    }
  }, [])

  const handleReset = () => {
    setState('idle')
    setData(null)
    setError(null)
    setCurrentDomains({ a: '', b: '' })
  }

  return (
    <div className="the-combinatoria">
      <SiteNav isToolPage />

      <header className="combinatoria-header">
        <h1 className="combinatoria-title" onClick={handleReset} style={{ cursor: 'pointer' }}>
          The Ars Combinatoria
        </h1>
        <p className="combinatoria-subtitle">
          Pick two fields. See what ideas exist at the intersection.
          <HelpTooltip text="Inspired by Ramon Llull's 1305 mechanical combination wheels — devices designed to systematically combine concepts and generate new knowledge. Pick two domains, and discover projects, techniques, and insights that exist only where they collide." />
        </p>
      </header>

      <main className="combinatoria-main">
        {/* Domain selector — always visible unless showing results */}
        {state !== 'results' && (
          <DomainSelector
            onCollide={handleCollide}
            isLoading={state === 'loading'}
            initialDomainA={domainAFromUrl || ''}
          />
        )}

        {/* Idle */}
        {state === 'idle' && (
          <div className="combinatoria-empty">
            <p className="combinatoria-empty-text">
              Pick two domains, or spin both and see what collides.
            </p>
            <p className="combinatoria-empty-hint">
              The more unrelated, the more interesting the results.
            </p>
          </div>
        )}

        {/* Loading */}
        {state === 'loading' && (
          <CombinatoriLoader />
        )}

        {/* Results */}
        {state === 'results' && data && (
          <div className="combinatoria-results">
            <div className="combinatoria-results-header">
              <button className="combinatoria-back-btn" onClick={handleReset}>
                ← New Collision
              </button>
              <h2 className="combinatoria-domains">
                {data.domain_a}
                <span className="combinatoria-domains-x">×</span>
                {data.domain_b}
              </h2>
            </div>

            {data.collision_point && (
              <div className="collision-point">
                <span className="collision-point-label">Collision Point</span>
                <p>{data.collision_point}</p>
              </div>
            )}

            {data.results.map((result, i) => (
              <CollisionCard key={result.title} result={result} index={i} />
            ))}

            {data.llull_note && (
              <div className="llull-note">
                <span className="llull-note-label">Llull's Note</span>
                <p>{data.llull_note}</p>
                <span className="llull-note-attribution">— The Ars Combinatoria</span>
              </div>
            )}

            <div className="combinatoria-copy">
              <button className="combinatoria-copy-btn" onClick={handleCopy}>
                {copied ? '✓ Copied to clipboard' : '⟢ Keep These Collisions'}
              </button>
              <span className="combinatoria-copy-hint">Copy as markdown</span>
            </div>
          </div>
        )}

        {/* Error */}
        {state === 'error' && (
          <div className="combinatoria-error">
            <p className="combinatoria-error-message">{error}</p>
            <button className="combinatoria-retry-btn" onClick={() => handleCollide(currentDomains.a, currentDomains.b)}>
              Try Again
            </button>
            <button className="combinatoria-back-btn" onClick={handleReset} style={{ display: 'block', margin: '0.5rem auto' }}>
              ← Start Over
            </button>
          </div>
        )}
      </main>

      {state === 'results' && data && (
        <>
          <div className="contextual-link-container">
            <Link
              to={`/decoder`}
              className="contextual-link"
            >
              Need to explain this to someone? →
            </Link>
          </div>
          <JourneyLink currentRoute="/combinatoria" />
        </>
      )}
      <SiteFooter />
    </div>
  )
}
